# Generated by Django 5.1.7 on 2025-04-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=20, null=True)),
                ('partner_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
