# Generated by Django 5.1.7 on 2025-04-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='last_name',
        ),
    ]
