# Generated by Django 5.1.7 on 2025-04-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_rename_title_partners_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='area',
            field=models.CharField(blank=True, choices=[('Sustainability', 'Sustainability'), ('Urban Resilience', 'Urban Resilience'), ('Environmental Conservation', 'Environmental Conservation'), ('Local Business', 'Local Business'), ('Sustainable Agriculture', 'Sustainable Agriculture')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='partner_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
