# Generated by Django 5.1.7 on 2025-04-06 00:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partners_area_alter_partners_partner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
