# Generated by Django 5.1.7 on 2025-04-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partners_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/partners/'),
        ),
    ]
